debug: true

server:
  port: 8080
spring:
  security:
    user:
      roles: DEV
      name: dev
      password: dev
    oauth2:
      client:
        registration:
          uaa-client:
            provider: uaa
            client-id: spring-security-expansion-sample
            client-secret: sample
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/login/oauth2/client/{registrationId}"
          uaa-password:
            provider: uaa
            client-id: spring-security-expansion-sample
            client-secret: sample
            authorization-grant-type: password
            redirect-uri: "{baseUrl}/login/oauth2/client/{registrationId}"
          uaa-authorization-code:
            provider: uaa
            client-id: spring-security-expansion-sample
            client-secret: sample
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/client/{registrationId}"
          uaa-sso:
            provider: uaa
            client-id: spring-security-expansion-sample
            client-secret: sample
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/"
        provider:
          uaa:
            authorization-uri: http://ds1019plus:16666/oauth/authorize
            token-uri: http://ds1019plus:16666/oauth/token
            user-info-uri: http://ds1019plus:16666/userinfo
            user-name-attribute: user_name
            client-info-uri: http://ds1019plus:16666/clientinfo
            client-id-attribute: client_id

logging:
  level:
    org.springframework.security: DEBUG
